name: pdp_quiz_app_with_my_backand
description: "PDP Quiz App with my backand"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  d_navigation_bar: ^0.0.1
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.2.1
  dio: ^5.5.0+1
  shimmer: ^3.0.0
  file_picker: ^8.0.6
  zoom_tap_animation: ^1.1.0
  web_socket_channel: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Black.ttf
        - asset: assets\fonts\Poppins-BlackItalic.ttf
        - asset: assets\fonts\Poppins-Bold.ttf
        - asset: assets\fonts\Poppins-BoldItalic.ttf
        - asset: assets\fonts\Poppins-ExtraBold.ttf
        - asset: assets\fonts\Poppins-ExtraBoldItalic.ttf
        - asset: assets\fonts\Poppins-ExtraLight.ttf
        - asset: assets\fonts\Poppins-ExtraLightItalic.ttf
        - asset: assets\fonts\Poppins-Italic.ttf
        - asset: assets\fonts\Poppins-Light.ttf
        - asset: assets\fonts\Poppins-LightItalic.ttf
        - asset: assets\fonts\Poppins-Medium.ttf
        - asset: assets\fonts\Poppins-MediumItalic.ttf
        - asset: assets\fonts\Poppins-Regular.ttf
        - asset: assets\fonts\Poppins-SemiBold.ttf
        - asset: assets\fonts\Poppins-SemiBoldItalic.ttf
        - asset: assets\fonts\Poppins-Thin.ttf
        - asset: assets\fonts\Poppins-ThinItalic.ttf
